name: sfbottle
description: "smart water bottle."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  flutter_datetime_picker: ^1.5.1
  mqtt_client: ^10.3.0
  firebase_core: ^3.3.0  # Compatible with older firebase_auth versions
  firebase_auth: ^5.1.4 # Compatible with firebase_core ^1.10.0
  cloud_firestore: ^5.2.1  # Ensure compatibility with firebase_core
  fluttertoast: ^8.1.0
  flutter_launcher_icons: ^0.13.1
  rive: ^0.13.13
  fl_chart: ^0.69.0
  geolocator: ^10.0.0
  geocoding: ^2.1.0
  flutter_local_notifications: ^15.1.3
  timezone: ^0.9.1
  intl: ^0.18.1 







  cupertino_icons: ^1.0.8

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon2.png

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/rive/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
